// This file is auto-generated. Do not edit manually.
export const DepartmentMapping: Record<string, string> = {
  "55DZ": "Optometry and Vision Science",
  "30GC": "Electrical and electronics engineering",
  "52HP": "Telecommunication Science",
  "56EB": "Mathematics",
  "30GT": "FOOD ENGINEERING",
  "55EH": "Biochemistry",
  "52HA": "Computer science",
  "25SC": "Social studies",
  "66RP": "Management Science",
  "30GD": "Mechanical Engineering",
  "52HT": "Information technology",
  "15CJ": "Religion",
  "66MB": "Finance",
  "10AC": "Agriculture",
  "52HL": "INFORMATION TECHNOLOGY",
  "30GQ": "Water Resources and Environmental Engineering",
  "77JB": "Geography and environmental management",
  "15CI": "Religions studies",
  "56ED": "Physics",
  "31QD": "Architecture",
  "40IL": "Law",
  "30GM": "Chemical Engineering",
  "21PN": "Pharmacy",
  "25PE": "Science Education",
  "66MA": "Accounting",
  "55EK": "Zoology",
  "77JH": "Criminology and security studies",
  "30GB": "Civil Engineering",
  "30GCO": "Electrical and electronic engineering",
  "10AS": "Forestry & wildlife management",
  "15CB": "Linguistics",
  "56EG": "Statistics",
  "30GN": "Metallurgical and materials engineering",
  "25PJ": "Educational technology",
  "47PT": "PHYSIOTHERAPY",
  "25OE": "Educational management",
  "56EE": "Chemistry",
  "15CA": "History and international studies",
  "77JD": "SOCIOLOGY",
  "25OW": "History education",
  "56FJ": "Geophysics",
  "66MC": "BUSINESS ADMINISTRATION",
  "56EA": "Geology",
  "30GP": "Biomedical engineering",
  "52HN": "Mass communication",
  "56EF": "Industrial Chemistry",
  "32TA": "Vet medicine",
  "25ST": "Social Sciences Education",
  "30GR": "Computer Engineering",
  "66RM": "public administration",
  "25OS": "Economics edu",
  "25PA": "Edu & Biology",
  "40IA": "Common law",
  "25PC": "Educational technology",
  "77JF": "Social Work",
  "31QE": "Estate Management",
  "25PM": "Business Education",
  "31QQ": "Surveying and Geoinformatics",
  "10AR": "Home economic",
  "46KA": "Biochemistry",
  "77JC": "Political science",
  "15CD": "English Department",
  "30GA": "Agricultural and Biosystems Engineering",
  "25PX": "Educational technology",
  "52HJ": "Library and information science",
  "55EJ": "Microbiology",
  "15CF": "Performing and film arts",
  "55EI": "Plant Biology",
  "66MG": "Marketing",
  "30GDO": "Mechanical engineering",
  "25PK": "Adult education",
  "77JA": "Economic",
  "25OT": "ENGLISH EDUCATION",
  "10AQ": "Home economics and Food science",
  "31QS": "Quantity survey",
  "46KB": "MEDICINE AND SURGERY",
  "10AB": "AQUACULTURE AND FISHERIES",
  "25PD": "Science education",
  "77JE": "Psychology",
  "48KC": "Medicine and Surgery",
  "25PU": "Educational Technology",
  "48LM": "Nursing",
  "25OY": "Primary education studies"
};

export function getDepartmentFromMatric(matric: string): string | null {
  const match = matric.match(/^\d{2}\/([A-Z0-9]+?)\/?\d+$/i);
  if (match) {
    const code = match[1].toUpperCase();
    return DepartmentMapping[code] || null;
  }
  return null;
}
